import Head from 'next/head'
import Image from 'next/image'
import { Permanent_Marker } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TaskTable from './taskTable'
import InputForm from './inputForm'
import { Text } from "@nextui-org/react";

const permanentMarker = Permanent_Marker({
  weight: '400',
  subsets: ['latin'],
  style: ['normal'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text h1
          className={`${styles.left} ${permanentMarker.className}`}
          size={42}
          css={{
            textGradient: "45deg, $blue600 -20%, $pink600 40%, $yellow600 100%",
          }}
          weight="bold"
        >Create your todo list here !!</Text>
        <InputForm></InputForm>
        <TaskTable></TaskTable>
      </main>
    </>
  )
}
